src/Entity/Annonce.php
<?php

namespace App\Entity;

use App\Repository\AnnonceRepository;
use Doctrine\Common\Collections\ArrayCollection;
use Doctrine\Common\Collections\Collection;
use Doctrine\DBAL\Types\Types;
use Doctrine\ORM\Mapping as ORM;

#[ORM\Entity(repositoryClass: AnnonceRepository::class)]
class Annonce
{
    #[ORM\Id]
    #[ORM\GeneratedValue]
    #[ORM\Column]
    private ?int $id = null;

    #[ORM\Column(length: 255)]
    private ?string $title = null;

    #[ORM\Column(type: Types::TEXT)]
    private ?string $description = null;

    #[ORM\Column(length: 255)]
    private ?string $model = null;

    #[ORM\Column]
    private ?float $price = null;

    #[ORM\Column]
    private ?int $year = null;

    #[ORM\Column]
    private ?float $km = null;

    #[ORM\Column(length: 255)]
    private ?string $fuel = null;

    #[ORM\Column]
    private ?bool $license = null;

    #[ORM\Column(length: 255)]
    private ?string $imgfile = null;

    #[ORM\Column]
    private ?bool $is_visible = null;

    #[ORM\ManyToOne(inversedBy: 'annonces')]
    private ?Marque $marque = null;

    #[ORM\ManyToOne(inversedBy: 'annonces')]
    private ?User $author = null;

    #[ORM\OneToMany(mappedBy: 'annonces', targetEntity: AnnonceListByUser::class)]
    private Collection $usersFav;

    public function __construct()
    {
        $this->usersFav = new ArrayCollection();
    }

    public function getId(): ?int
    {
        return $this->id;
    }

    public function getTitle(): ?string
    {
        return $this->title;
    }

    public function setTitle(string $title): self
    {
        $this->title = $title;

        return $this;
    }

    public function getDescription(): ?string
    {
        return $this->description;
    }

    public function setDescription(string $description): self
    {
        $this->description = $description;

        return $this;
    }

    public function getModel(): ?string
    {
        return $this->model;
    }

    public function setModel(string $model): self
    {
        $this->model = $model;

        return $this;
    }

    public function getPrice(): ?float
    {
        return $this->price;
    }

    public function setPrice(float $price): self
    {
        $this->price = $price;

        return $this;
    }

    public function getYear(): ?int
    {
        return $this->year;
    }

    public function setYear(int $year): self
    {
        $this->year = $year;

        return $this;
    }

    public function getKm(): ?float
    {
        return $this->km;
    }

    public function setKm(float $km): self
    {
        $this->km = $km;

        return $this;
    }

    public function getFuel(): ?string
    {
        return $this->fuel;
    }

    public function setFuel(string $fuel): self
    {
        $this->fuel = $fuel;

        return $this;
    }

    public function isLicense(): ?bool
    {
        return $this->license;
    }

    public function setLicense(bool $license): self
    {
        $this->license = $license;

        return $this;
    }

    public function getImgfile(): ?string
    {
        return $this->imgfile;
    }

    public function setImgfile(string $imgfile): self
    {
        $this->imgfile = $imgfile;

        return $this;
    }

    public function getIsVisible(): ?bool
    {
        return $this->is_visible;
    }

    public function setIsVisible(bool $is_visible): self
    {
        $this->is_visible = $is_visible;

        return $this;
    }

    public function getMarque(): ?Marque
    {
        return $this->marque;
    }

    public function setMarque(?Marque $marque): self
    {
        $this->marque = $marque;

        return $this;
    }

    public function getAuthor(): ?User
    {
        return $this->author;
    }

    public function setAuthor(?User $author): self
    {
        $this->author = $author;

        return $this;
    }

    /**
     *
     * @param User $user
     * @return boolean
     */
    public function isUserFav(User $user) : bool
    {
        foreach($this->usersFav as $usersFav) {
            if($usersFav->getUsers() === $user) return true;
        }
        return false;
    }

    /**
     * @return Collection<int, AnnonceListByUser>
     */
    public function getUsersFav(): Collection
    {
        return $this->usersFav;
    }

    public function addUsersFav(AnnonceListByUser $usersFav): self
    {
        if (!$this->usersFav->contains($usersFav)) {
            $this->usersFav->add($usersFav);
            $usersFav->setAnnonces($this);
        }

        return $this;
    }

    public function removeUsersFav(AnnonceListByUser $usersFav): self
    {
        if ($this->usersFav->removeElement($usersFav)) {
            // set the owning side to null (unless already changed)
            if ($usersFav->getAnnonces() === $this) {
                $usersFav->setAnnonces(null);
            }
        }

        return $this;
    }    
}

src/Controller/MainController.php
<?php

namespace App\Controller;

use App\Entity\Marque;
use App\Repository\AnnonceRepository;
use App\Repository\MarqueRepository;
use App\Repository\UserRepository;
use Symfony\Bundle\FrameworkBundle\Controller\AbstractController;
use Symfony\Component\HttpFoundation\Response;
use Symfony\Component\Routing\Annotation\Route;

class MainController extends AbstractController
{
    #[Route('/', name: 'home')]
    public function index(AnnonceRepository $annonceRepository, UserRepository $userRepository, MarqueRepository $marqueRepository): Response
    {
        return $this->render('main/index.html.twig', [
            "annonces" => $annonceRepository->findBy([
                'is_visible' => true
        ]),
            "marques" => $marqueRepository->findAll()
        ]);
    }

    #[Route('/card/{id}', name: 'marque', methods: ['GET'])]
    public function marque(Marque $marque, AnnonceRepository $annonceRepository): Response
    {
        return $this->render('main/marque.html.twig', [
            "marque" => $marque,
            "annonces" => $annonceRepository->findAll()
        ]);
    }
}

templates/main/index.html.twig
{% extends 'base.html.twig' %}

{% block title %}Blog auto{% endblock %}

{% block body %}

<div class="container mt-4">
    <h2 class="text-center">La voiture de vos rêves est à portée de clic... Saisissez-là !</h2>

    {% include "components/menu.html.twig" %}

    {% if app.user %}
        <div class="d-flex justify-content-center mt-2">
            <a type="button" class="btn btn-success btn-sm" href="/annonce/new">Ajouter une annonce</a>
        </div>
        
        {% if is_granted('ROLE_ADMIN') %}
            <div class="d-flex justify-content-center gap-2 mt-2">
                <a href="/annonce" type="button" class="btn btn-warning btn-sm">Liste des annonces</a>
                <a href="/admin/marque" type="button" class="btn btn-warning btn-sm">Liste des marques</a>
            </div>
        {% endif %}
    {% endif %}

    <div class="container d-flex flex-wrap gap-3 mt-4">
        {% for annonce in annonces %}
            <div class="container d-flex flex-column align-items-end" style="width: 18rem;">
                {% if app.user %}
                    {% for role in app.user.roles %}
                        {% if role == 'ROLE_ADMIN' %}
                            <div class="btn-group-sm" role="group">
                                <a class="btn btn-warning my-1" style=" --bs-btn-font-size: .75rem;" href="{{path('app_annonce_edit', {'id' : annonce.id}) }}">Edit</a>
                                <a class="btn btn-danger my-1" style="--bs-btn-font-size: .75rem;" href="{{path('app_annonce_delete', {'id' : annonce.id}) }}">Delete</a>
                            </div>
                        {% endif %}
                    {% endfor %}
                {% endif %}

                <div class="card" style="width: 18rem;">
                    {# <img class="card-img-top" src=" {{asset('images_directory/' ~ annonce.imgfile )}}" alt="Card image cap"/> #}
                    <img class="card-img-top" src="{{ annonce.imgfile }}" alt="Card image cap"/>
                    <div class="card-body">
                        <h5 class="card-title">{{ annonce.title|u.truncate(20, '...')}}</h5>
                        <p class="card-text">{{ annonce.description|u.truncate(30,'...')|raw }}</p>
                        <a href="{{path('app_annonce_show', {'id' : annonce.id}) }}" class="btn btn-primary" >Détails</a>
                        {% if app.user %}
                            <a type="button" class="btn btn-outline-light w-30" href="{{path('app_annonce_fav', {'id' : annonce.id}) }}">
                                {% if annonce.isUserFav(app.user) %}
                                    <img class="favoris" src="/images_directory/etoile-pleine.png" alt="etoile pleine">
                                {% else %}
                                    <img class="favoris" src="/images_directory/etoile-vide.png" alt="etoile vide">
                                {% endif %}
                            </a>
                        {% endif %}
                    </div>
                </div>
            </div>
        {% endfor %}
    </div>
</div>
{% endblock %}

templates/main/marque.html.twig
{% extends 'base.html.twig' %}

{% block title %}Blog auto{% endblock %}

{% block body %}
<div class="container mt-4">
    
    {% include "components/menu.html.twig" %}
    <div class="container d-flex flex-wrap gap-3 mt-4">
            
        {% for annonce in marque.annonces %}
            {% if annonce.isVisible %}
                <div class="container d-flex flex-column align-items-end" style="width: 18rem;">
                    {% if app.user %}
                        {% for role in app.user.roles %}
                            {% if role == 'ADMIN' %}
                                <div class="btn-group-sm" role="group">
                                    <a class="btn btn-warning my-1" style=" --bs-btn-font-size: .75rem;" href="{{path('app_annonce_edit', {'id' : annonce.id}) }}">Edit</a>
                                    <a class="btn btn-danger my-1" style="--bs-btn-font-size: .75rem;" href="{{path('app_annonce_delete', {'id' : annonce.id}) }}">Delete</a>
                                </div>
                            {% endif %}
                        {% endfor %}
                    {% endif %}

                    <div class="card" style="width: 18rem;">
                        {# <img class="card-img-top" src="{{asset('images_directory/' ~ annonce.imgfile )}}" alt="Card image cap"> #}
                        <img class="card-img-top" src="{{ annonce.imgfile }}" alt="Card image cap"/>
                        <div class="card-body">
                            <h5 class="card-title">{{ annonce.title }}</h5>
                            <p class="card-text">{{ annonce.description|raw }}</p>
                            <a href="{{path('app_annonce_show', {'id' : annonce.id}) }}" class="btn btn-primary" style="--bs-btn-bg: #339af0;">Détails</a>
                            <a type="button" class="btn btn-outline-light w-30" href="{{path('app_annonce_fav', {'id' : annonce.id}) }}">
                            {% if annonce.isUserFav(app.user) %}
                                <img class="favoris" src="/images_directory/etoile-pleine.png" alt="etoile pleine">
                            {% else %}
                                <img class="favoris" src="/images_directory/etoile-vide.png" alt="etoile vide">
                            {% endif %}
                        </a>
                        </div>
                    </div>
                </div>
            {% endif %}
        {% endfor %}

    </div>
</div>

{% endblock %}